TRAINING_MONITOR_METRIC_DICE_MACRO = "dice_coef_macro"
TRAINING_MONITOR_METRIC_DICE_MICRO = "dice_coef_micro"

EVALUATION_METRIC_DICE_CLASSES = "dice_coef_classes"
EVALUATION_METRIC_DICE_MACRO = "dice_coef_macro"
EVALUATION_METRIC_DICE_MICRO = "dice_coef_micro"
EVALUATION_METRIC_AVERAGE_SURFACE_DISTANCE = "average_surface_distance"
EVALUATION_METRIC_HAUSDORFF_DISTANCE = "hausdorff_distance"

EVALUATION_METRICS = set(
    [
        EVALUATION_METRIC_DICE_CLASSES,
        EVALUATION_METRIC_DICE_MACRO,
        EVALUATION_METRIC_DICE_MICRO,
        EVALUATION_METRIC_AVERAGE_SURFACE_DISTANCE,
        EVALUATION_METRIC_HAUSDORFF_DISTANCE,
    ]
)

AUG_MODE_NONE = "none"
AUG_MODE_ONE = "one"
AUG_MODE_ALL = "all"

AUG_MODES = [AUG_MODE_NONE, AUG_MODE_ONE, AUG_MODE_ALL]
